name: Take a Screenshot

on:
   workflow_dispatch:
   schedule:
    - cron: '0 */4 * * *'

jobs:
  Screenshotter:
    runs-on: ubuntu-latest
    steps:
      - name: Check out this repo
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Installed package list
        run: apt list --installed
      - name: Remove Chrome
        run: sudo apt purge google-chrome-stable
      # Chromium is already installed!
      # - name: Install software
      #   run: sudo apt install -y chromium-browser
      - name: Install all necessary packages
        run: pip install requests beautifulsoup4 pandas chromedriver-autoinstaller selenium pyvirtualdisplay 
      - name: Install xvfb
        run: sudo apt-get install xvfb
      - name: Run the scraping script
        working-directory: ./
        run: |
         INPUT_STORE=${{"index.html,"}} INPUT_STORE2=${{" " }} INPUT_STORE3=${{ "File" }}  INPUT_STORE4=${{ github.event.repository.name }} python screenshotter.py
    

      - name: Commit and Push
        run: |
         git config --global user.name "github-actions[bot]"
         git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
         git add -A
         git commit -m "Screenshot added"
         git push
